In [353]:
# ignore warnings
import warnings
warnings.filterwarnings("ignore")

import numpy as np

from pydataset import data

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import env
import acquire

In [583]:
df = acquire.get_telco_churn_data()

In [584]:
df.head()

customer_id  gender  senior_citizen partner dependents  tenure  \
0  0002-ORFBO  Female               0     Yes        Yes       9   
1  0003-MKNFE    Male               0      No         No       9   
2  0004-TLHLJ    Male               0      No         No       4   
3  0011-IGKFF    Male               1     Yes         No      13   
4  0013-EXCHZ  Female               1     Yes         No       3   

  phone_service multiple_lines  internet_service_type_id online_security  ...  \
0           Yes             No                         1              No  ...   
1           Yes            Yes                         1              No  ...   
2           Yes             No                         2              No  ...   
3           Yes             No                         2              No  ...   
4           Yes             No                         2              No  ...   

  device_protection tech_support streaming_tv streaming_movies  \
0                No          Yes          Yes               No   
1                No           No           No              Yes   
2               Yes           No           No               No   
3               Yes           No          Yes              Yes   
4                No          Yes          Yes               No   

  contract_type_id  paperless_billing payment_type_id  monthly_charges  \
0                2                Yes               2             65.6   
1                1                 No               2             59.9   
2                1                Yes               1             73.9   
3                1                Yes               1             98.0   
4                1                Yes               2             83.9   

   total_charges churn  
0          593.3    No  
1          542.4    No  
2         280.85   Yes  
3        1237.85   Yes  
4          267.4   Yes  

[5 rows x 21 columns]

In [585]:
df.isnull().sum()

customer_id                 0
gender                      0
senior_citizen              0
partner                     0
dependents                  0
tenure                      0
phone_service               0
multiple_lines              0
internet_service_type_id    0
online_security             0
online_backup               0
device_protection           0
tech_support                0
streaming_tv                0
streaming_movies            0
contract_type_id            0
paperless_billing           0
payment_type_id             0
monthly_charges             0
total_charges               0
churn                       0
dtype: int64

In [586]:
df.describe()

senior_citizen       tenure  internet_service_type_id  \
count     7043.000000  7043.000000               7043.000000   
mean         0.162147    32.371149                  1.872923   
std          0.368612    24.559481                  0.737796   
min          0.000000     0.000000                  1.000000   
25%          0.000000     9.000000                  1.000000   
50%          0.000000    29.000000                  2.000000   
75%          0.000000    55.000000                  2.000000   
max          1.000000    72.000000                  3.000000   

       contract_type_id  payment_type_id  monthly_charges  
count       7043.000000      7043.000000      7043.000000  
mean           1.690473         2.315633        64.761692  
std            0.833755         1.148907        30.090047  
min            1.000000         1.000000        18.250000  
25%            1.000000         1.000000        35.500000  
50%            1.000000         2.000000        70.350000  
75%            2.000000         3.000000        89.850000  
max            3.000000         4.000000       118.750000

In [587]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customer_id                 7043 non-null object
gender                      7043 non-null object
senior_citizen              7043 non-null int64
partner                     7043 non-null object
dependents                  7043 non-null object
tenure                      7043 non-null int64
phone_service               7043 non-null object
multiple_lines              7043 non-null object
internet_service_type_id    7043 non-null int64
online_security             7043 non-null object
online_backup               7043 non-null object
device_protection           7043 non-null object
tech_support                7043 non-null object
streaming_tv                7043 non-null object
streaming_movies            7043 non-null object
contract_type_id            7043 non-null int64
paperless_billing           7043 non-null object
payment_type_id             7043 non-null int64
monthly_charges 

In [588]:
df.size

147903

In [589]:
df.shape

(7043, 21)

In [590]:
df['churn'] = df['churn'].replace('Yes', 1)
df['churn'] = df['churn'].replace('No', 0)

In [591]:
df.head()

customer_id  gender  senior_citizen partner dependents  tenure  \
0  0002-ORFBO  Female               0     Yes        Yes       9   
1  0003-MKNFE    Male               0      No         No       9   
2  0004-TLHLJ    Male               0      No         No       4   
3  0011-IGKFF    Male               1     Yes         No      13   
4  0013-EXCHZ  Female               1     Yes         No       3   

  phone_service multiple_lines  internet_service_type_id online_security  ...  \
0           Yes             No                         1              No  ...   
1           Yes            Yes                         1              No  ...   
2           Yes             No                         2              No  ...   
3           Yes             No                         2              No  ...   
4           Yes             No                         2              No  ...   

  device_protection tech_support streaming_tv streaming_movies  \
0                No          Yes          Yes               No   
1                No           No           No              Yes   
2               Yes           No           No               No   
3               Yes           No          Yes              Yes   
4                No          Yes          Yes               No   

  contract_type_id  paperless_billing payment_type_id  monthly_charges  \
0                2                Yes               2             65.6   
1                1                 No               2             59.9   
2                1                Yes               1             73.9   
3                1                Yes               1             98.0   
4                1                Yes               2             83.9   

   total_charges churn  
0          593.3     0  
1          542.4     0  
2         280.85     1  
3        1237.85     1  
4          267.4     1  

[5 rows x 21 columns]

In [592]:
# df['total_charges'] = pd.to_numeric(df['total_charges'], errors='coerce')
# df.total_charges = df.total_charges.astype(str).str.strip().replace({'nan': np.nan})

In [593]:
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df["total_charges"] = df["total_charges"].astype('float')
df = df.dropna()
# df = df.drop(columns="customer_id")

In [594]:
df.shape

(7032, 21)

In [595]:
X = df[['senior_citizen', 'tenure', 'internet_service_type_id', 'contract_type_id', 'payment_type_id', 'monthly_charges', 'total_charges']]

In [596]:
y = df[['churn']]

In [611]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .20, random_state = 123)

X_train.head()

senior_citizen  tenure  internet_service_type_id  contract_type_id  \
5483               0      15                         2                 1   
5436               0      71                         1                 3   
3572               0      32                         1                 1   
2100               0      19                         3                 1   
7019               0      71                         2                 3   

      payment_type_id  monthly_charges  total_charges  
5483                3             68.6        1108.60  
5436                2             80.1        5585.40  
3572                3             61.4        1864.65  
2100                1             20.0         377.55  
7019                3            106.7        7382.25

In [612]:
y_train.head()

churn
5483      0
5436      0
3572      0
2100      0
7019      0

In [613]:
clf = DecisionTreeClassifier(max_depth=4, random_state=123)

In [614]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [615]:
y_train.dtypes

churn    int64
dtype: object

In [616]:
y_pred = clf.predict(X_train)
y_pred[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1])

In [603]:
y_pred_proba = clf.predict_proba(X_train)
y_pred_proba

array([[0.76290323, 0.23709677],
       [0.9888664 , 0.0111336 ],
       [0.76290323, 0.23709677],
       ...,
       [0.52147239, 0.47852761],
       [0.925     , 0.075     ],
       [0.925     , 0.075     ]])

In [604]:
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))

Accuracy of Decision Tree classifier on training set: 0.80


In [605]:
confusion_matrix(y_train, y_pred)

array([[3742,  384],
       [ 760,  739]])

In [606]:
sorted(y_train.churn.unique())

[0, 1]

In [607]:
y_train.churn.value_counts()

0    4126
1    1499
Name: churn, dtype: int64

In [608]:
labels = sorted(y_train.churn.unique())

pd.DataFrame(confusion_matrix(y_train, y_pred), index=labels, columns=labels)

0    1
0  3742  384
1   760  739

Create a classification report
Precision: the higher this number is, the more you were able to pinpoint all positives correctly. If this is a low score, you predicted a lot of positives where there were none. tp / (tp + fp)
Recall: if this score is high, you didn’t miss a lot of positives. But as it gets lower, you are not predicting the positives that are actually there. tp / (tp + fn)
f1-score: The balanced harmonic mean of Recall and Precision, giving both metrics equal weight. The higher the F-Measure is, the better.
Support: number of occurrences of each class in where y is true.

In [609]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      4126
           1       0.66      0.49      0.56      1499

    accuracy                           0.80      5625
   macro avg       0.74      0.70      0.72      5625
weighted avg       0.79      0.80      0.79      5625



In [617]:
cm = pd.DataFrame(confusion_matrix(y_train, y_pred))
FP = cm.sum(axis=0) - np.diag(cm)  
FN = cm.sum(axis=1) - np.diag(cm)
TP = np.diag(cm)
TN = cm.values.sum() - (FP + FN + TP)
# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
# Specificity or true negative rate
TNR = TN/(TN+FP) 
# Precision or positive predictive value
PPV = TP/(TP+FP)
# Negative predictive value
NPV = TN/(TN+FN)
# Fall out or false positive rate
FPR = FP/(FP+TN)
# False negative rate
FNR = FN/(TP+FN)
# False discovery rate
FDR = FP/(TP+FP)
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)

In [623]:
print(NPV)
print(FPR)

0    0.658059
1    0.831186
dtype: float64
0    0.507005
1    0.093068
dtype: float64


In [610]:
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on test set: 0.79
